language: node_js

node_js:
  # Supported versions
  - "10"
  - "12"
  # Latest stable
  - "node"

# Deploy on tags

deploy:
  provider: npm
  email: $NPME
  api_key: $NPMP
  on:
    tags: true
    node_js: 10

# Run tests

install:
  - npm install
jobs:
  include:
    - stage: Coverage
      node_js: 10
      script: npm run coverage:all
